SELECT ELAPSED_TIME_MIN,
SUBSTR(AUTHID,1,10) AS APPL_AUTH_ID,
AGENT_ID as Long_running_APPL_Handle,
APPL_STATUS,
SUBSTR(STMT_TEXT,1,950) AS Long_Runnning_SQL_TEXT
--SUBSTR(STMT_TEXT,1,50) AS Current_Long_Runnning_SQL_TEXT
FROM SYSIBMADM.LONG_RUNNING_SQL
WHERE
ELAPSED_TIME_MIN > 0
--and
--APPL_STATUS <> 'UOWWAIT'
and STMT_TEXT not like '%ICMSEARCH%'
ORDER BY ELAPSED_TIME_MIN DESC
--fetch first 10 rows only
;
