SELECT AGENT_ID,SUBSTR(APPL_NAME,1,10) AS APPL_NAME,SUBSTR(AUTHID,1,10) as AUTH_ID,substr(APPL_STATUS,1,10) as APPL_STATUS,STATUS_CHANGE_TIME, CLIENT_PID,substr(CLIENT_NNAME,1,10) as Client_NName 
FROM SYSIBMADM.APPLICATIONS
where 
--DB_NAME = 'ICMNLSDB' and 
--APPL_STATUS in ( 'UOWEXEC','LOCKWAIT','BACKUP','COMMIT_ACT','CONNECTED','LOAD')
--APPL_STATUS <> 'UOWWAIT'
APPL_STATUS not in ('UOWWAIT','CONNECTED')
--APPL_STATUS = 'UOWWAIT'
and current_timestamp > (status_change_time + 60 minutes) 
and AUTHID <> 'DB2INST1'
;   
--
--select a.agent_id,substr(a.appl_name,1,10) as APPL_NAME,substr(a.AUTHID,1,10) as AUTH_ID,substr(a.APPL_STATUS,1,10) as APPL_STATUS,a.STATUS_CHANGE_TIME,aprm.PERCENT_ROWS_SELECTED from SYSIBMADM.APPLICATIONS a, SYSIBMADM.APPL_PERFORMANCE aprm where a.agent_id=aprm.agent_id;
